server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog-logger
    static_configs:
      - targets:
          - flog-logger
        labels:
          job: flog
          __path__: /var/log/flog.log